version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/products/license"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/products/easysearch"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/products/tongsuo"
    schedule:
      interval: "weekly"      