name: coco-ai
base: core22
version: '__VERSION__'
summary: Coco-AI
contact: hello@infini.ltd
license: MIT
description: |
  🥥 Coco AI App - Search, Connect, Collaborate, Your Personal AI Search and Assistant, all in one space.
grade: stable
confinement: strict
layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1
apps:
  coco-ai:
    command: usr/bin/coco
    desktop: usr/share/applications/Coco-AI.desktop
    extensions: [gnome]

package-repositories:
  - type: apt
    components: [main]
    suites: [noble]
    key-id: 78E1918602959B9C59103100F1831DDAFC42E99D
    url: http://ppa.launchpad.net/snappy-dev/snapcraft-daily/ubuntu

parts:
  build-app:
    plugin: dump
    source: __SOURCE_DIR__/snap_sources/__APP_NAME__.deb
    source-type: deb
    override-build: |
      set -eu
      echo "Repack Coco AI App with ${SNAPCRAFT_PART_INSTALL} at ${PWD} .."
      dpkg -x __SOURCE_DIR__/snap_sources/__APP_NAME__.deb $SNAPCRAFT_PART_INSTALL/
      sed -i -e "s|Icon=coco|Icon=/usr/share/icons/hicolor/32x32/apps/coco.png|g" $SNAPCRAFT_PART_INSTALL/usr/share/applications/Coco-AI.desktop