name: coco-ai
base: core22
version: '__VERSION__'
summary: Coco-AI
contact: hello@infini.ltd
license: MIT
description: |
  🥥 Coco AI App - Search, Connect, Collaborate, Your Personal AI Search and Assistant, all in one space.
grade: stable
confinement: strict
layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1
apps:
  coco-ai:
    command: usr/bin/coco
    desktop: usr/share/applications/Coco-AI.desktop
    extensions: [gnome]
    plugs:
      - network

package-repositories:
  - type: apt
    components: [main]
    suites: [jammy]
    key-id: 78E1918602959B9C59103100F1831DDAFC42E99D
    url: http://ppa.launchpad.net/snappy-dev/snapcraft-daily/ubuntu

parts:
  build-app:
    plugin: dump
    build-snaps:
      - node/20/stable
      - rustup/latest/stable
    build-packages:
      - libwebkit2gtk-4.1-dev
      - build-essential
      - curl
      - wget
      - file
      - libxdo-dev
      - libssl-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - dpkg
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1
    source: .
    override-build: |
      set -eu
      echo "Repack Coco AI App with ${SNAPCRAFT_PART_INSTALL} at ${PWD} .."
      npm install -g pnpm --unsafe-perm || true
      pnpm run tauri build --target __TARGET__ --bundles deb
      echo "Extract deb package to ${SNAPCRAFT_PART_INSTALL} ..."

      if [ -d "$SNAPCRAFT_PART_INSTALL" ]; then
        echo "------------------------------------------------------------"
        ls -la $SNAPCRAFT_PART_INSTALL
        echo "------------------------------------------------------------"
        ls -la src-tauri/target/__TARGET__/release/bundle/deb
        echo "------------------------------------------------------------"
        ls -la $(pwd)
        echo "------------------------------------------------------------"
      fi

      if [ -e src-tauri/target/__TARGET__/release/bundle/deb/__APPNAME__.deb ]; then
        dpkg -x src-tauri/target/__TARGET__/release/bundle/deb/__APPNAME__.deb $SNAPCRAFT_PART_INSTALL
      fi
      
      if [ -f "$SNAPCRAFT_PART_INSTALL/usr/share/applications/Coco-AI.desktop" ]; then
        echo "Found desktop file, replace icon path ..."
        sed -i "s|^Icon=.*$|Icon=/usr/share/icons/hicolor/32x32/apps/coco.png|g" $SNAPCRAFT_PART_INSTALL/usr/share/applications/Coco-AI.desktop
      fi