name: coco
base: core22
version: '__VERSION__'
summary: 🥥 Coco AI App - Your Personal AI Search and Assistant.
contact: hello@infini.ltd
license: MIT
description: |
  🥥 Coco AI App - Search, Connect, Collaborate, Your Personal AI Search and Assistant, all in one space.
grade: stable
confinement: strict
layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1

apps:
  coco:
    command: usr/bin/coco
    desktop: usr/share/applications/Coco-AI.desktop
    extensions: [gnome]
    plugs:
      - home
      - network
      - audio-playback
      - audio-record

package-repositories:
  - type: apt
    components: [main]
    suites: [noble]
    key-id: 78E1918602959B9C59103100F1831DDAFC42E99D
    url: http://ppa.launchpad.net/snappy-dev/snapcraft-daily/ubuntu

parts:
  coco:
    plugin: dump
    build-snaps:
      - node/20/stable
      - rustup/latest/stable
    build-packages:
      - libwebkit2gtk-4.1-dev
      - build-essential
      - curl
      - unzip
      - wget
      - file
      - libxdo-dev
      - libssl-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - dpkg
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1
    source: .
    override-build: |
      set -eu
      export TAURI_SIGNING_PRIVATE_KEY="__PRIVATE_KEY__"
      export TAURI_SIGNING_PRIVATE_KEY_PASSWORD=""

      echo "Repack Coco AI App with ${SNAPCRAFT_PART_INSTALL} at ${PWD} .."
      npm install -g pnpm --unsafe-perm || true
      pnpm run tauri build --target __TARGET__ --bundles deb
      echo "Extract deb package to ${SNAPCRAFT_PART_INSTALL} ..."

      DEB_FILE="src-tauri/target/__TARGET__/release/bundle/deb/__APPARCHNAME__.deb"
      if [[ -e $DEB_FILE ]]; then
        echo "Found deb package at $DEB_FILE"
        dpkg -x $DEB_FILE $SNAPCRAFT_PART_INSTALL
        ls -l $SNAPCRAFT_PART_INSTALL
      else
        echo "Error: Deb package not found at $DEB_FILE!"
      fi
      
      DESKTOP_FILE="$SNAPCRAFT_PART_INSTALL/usr/share/applications/Coco-AI.desktop"
      if [[ -e $DESKTOP_FILE ]]; then
        echo "Found desktop file, replace icon path ..."
        sed -i "s|^Icon=.*$|Icon=/usr/share/icons/hicolor/128x128/apps/coco.png|g" $DESKTOP_FILE
      else
        echo "Warning: Desktop file not found, skipping icon path replacement."
      fi