name: Publish Pizza Website
defaults:
  run:
    shell: bash
env:
  TZ: Asia/Shanghai
  SNAME: pizza
  PNAME: pizza-website
  DNAME: pizza-website-publish
  HUGO_VERSION: ${{ vars.HUGO_VERSION }}
  NODEJS_VERSION: ${{ vars.NODEJS_EXT_VERSION }}

on:
  workflow_dispatch:
    inputs:
      PUBLISH_RELEASE:
        description: 'Publish Release'
        required: false
        type: boolean
        default: false

jobs:
  publish:
    name: Publish Pizza Webisite
    runs-on: ubuntu-latest
    env:
        OSS_EP: ${{ secrets.OSS_EP }}
        OSS_AK: ${{ secrets.OSS_AK }}
        OSS_SK: ${{ secrets.OSS_SK }}
        OSS_BK: ${{ secrets.OSS_BK }}
        OSS_MODE: ${{ secrets.OSS_MODE }}
        LOCAL_HOST: ${{ secrets.LOCAL_HOST }}
        LOCAL_PORT: ${{ secrets.LOCAL_PORT }}
        SSH_GIT_REPO: ${{ secrets.SSH_GIT_REPO }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_CONFIG: ${{ secrets.SSH_CONFIG }}
        CONNECT_SERVER: ${{ secrets.CONNECT_SERVER }}
        CONNECT_PORT: ${{ secrets.CONNECT_PORT }}
        CONNECT_KEY: ${{ secrets.CONNECT_KEY }}
        CONNECT_TIMEOUT: ${{ vars.CONNECT_TIMEOUT }}
        CONNECT_MODE: ${{ vars.CONNECT_MODE }}
        CONNECT_METHOD: ${{ secrets.CONNECT_METHOD }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup bootstrap
      uses: ./containers/bootstrap

    - name: Run connect in background for ${{env.PNAME}}
      run: |
        connect -c "$GITHUB_WORKSPACE/.net.json" >/dev/null 2>&1 &
        echo "Connect started with pid $!"
        sleep 5
  
    - name: Install Hugo
      run: |
        wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
        tar -xzf hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
        sudo mv hugo /usr/local/bin/

    - name: Checkout pizza repository
      uses: actions/checkout@v6
      with:
          repository: infinilabs/${{ env.SNAME }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ref: main
          path: ${{ env.SNAME }}
    
    - name: Checkout pizza website repository
      run: |
        git clone --depth 1 $SSH_GIT_REPO/$PNAME $GITHUB_WORKSPACE/$PNAME
        cd $GITHUB_WORKSPACE/$PNAME && echo Checkout $PNAME repo $(git log -1 --pretty=format:"%h, %ad" --date=iso)

    - name: Checkout publish pizza website repository
      uses: actions/checkout@v6
      with:
        ref: main
        repository: infinilabs/${{ env.PNAME }}
        path: ${{ env.DNAME }}
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v5
      with:
        version: latest

    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: ${{ env.NODEJS_VERSION }}
        check-latest: false

    - name: Restore cache
      uses: actions/cache@v5
      with:
        path: |
          .next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock', '**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock', '**/pnpm-lock.yaml') }}

    - name: Set up env
      run: |
        echo SRC=$GITHUB_WORKSPACE/$PNAME/out >> $GITHUB_ENV
        echo DEST=$GITHUB_WORKSPACE/public >> $GITHUB_ENV

    - name: Build docs Website
      working-directory: ${{ env.SNAME }}
      run: |
        echo "Build $SNAME docs to $DEST"
        mkdir -p $DEST
        ( cd website && hugo --minify --theme book --destination=$DEST )

    - name: Install dependencies
      working-directory: ${{ env.PNAME }}
      env:
        NPM_CONFIG_STRICT_SSL: "true" 
      run: |
        echo "registry=https://registry.npmmirror.com" > .npmrc
        pnpm install --quiet

    - name: Build Website
      working-directory: ${{ env.PNAME }}
      run: |
        echo "Build $PNAME"
        pnpm build
       
    - name: Merge website and docs
      run: |
        echo "Merge website and docs at $DEST"
        cp -rf $SRC/* $DEST
        (cd $DEST && touch .nojekyll)
        (cd $DEST && echo "pizza.rs" > CNAME)

    - name: Publish to github website repo
      if: ${{ inputs.PUBLISH_RELEASE }}
      run: |
        cd $DEST
        git init .

        git config user.name github-actions
        git config user.email github-actions@github.com

        git add . && git commit -m "init commit"
        git remote add origin git@github.com:infinilabs/pizza-website.git
        git branch -M main && git push -u origin main --force

    - name: Create zip archive
      run: |
        cd $DEST && pwd && ls -lrt .
        (cd $DEST && zip -qr ../$PNAME.zip .)

    - name: Deploy ${{env.PNAME}} to staging for check
      if: ${{ !inputs.PUBLISH_RELEASE }}
      timeout-minutes: 60
      continue-on-error: true
      run: |
        echo "Deploy zip file at `pwd`"
        if [[ -f $PNAME.zip ]]; then
          echo "Deploying $PNAME.zip to staging at $(date +'%m-%d %H:%M:%S')"
          rsync -avzP -e 'ssh -o Ciphers=aes128-gcm@openssh.com' $PNAME.zip staging:/opt
          echo "Uploaded $PNAME to staging at $(date +'%m-%d %H:%M:%S')"
        else
          echo "No $PNAME zip found"
        fi
        echo "Finished deploying $PNAME to staging at $(date +'%m-%d %H:%M:%S')"