name: Publish Operator Docker Image

defaults:
  run:
    shell: bash

env:
  TZ: Asia/Shanghai

on:
  schedule:
    - cron: '30 16 * * *'
  workflow_dispatch:
    inputs:
      PUBLISH_SEARCH:
        description: 'Publish easysearch & elasticsearch'
        required: false
        type: boolean
        default: true
      PUBLISH_RUNTIME:
        description: 'Publish runtime'
        required: false
        type: boolean
        default: true
      PUBLISH_RELEASE:
        description: 'Publish release'
        type: boolean
        required: false
        default: true        
      PUBLISH_VERSION:
        description: 'Publish version'
        required: true
        default: "1.6.0"

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      components: ${{ steps.set-components.outputs.components }}
    steps:
      - name: Set components for build
        id: set-components
        run: |
          # check publish version x.y.z
          
          # check inputs must search or runtime or both
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            if [[ ! "${{ inputs.PUBLISH_VERSION }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "Invalid version format. Expected x.y.z"
              exit 1
            fi
            # check if the inputs are set
            if [[ "${{ inputs.PUBLISH_SEARCH }}" == 'true' ]] && [[ "${{ inputs.PUBLISH_RUNTIME }}" == 'true' ]]; then
              COMPONENTS="search,runtime"
            elif [[ "${{ inputs.PUBLISH_SEARCH }}" == 'true' ]]; then
              COMPONENTS="search"
            elif [[ "${{ inputs.PUBLISH_RUNTIME }}" == 'true' ]]; then
              COMPONENTS="runtime"
            else
              echo "No components to build"
              exit 1
            fi
          else
            COMPONENTS="search,runtime"
          fi
          echo "components=$(echo $COMPONENTS | jq -Rc 'split(",")')" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

  publish:
    needs: setup
    name: Publish ${{ matrix.component }} Docker Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: ${{ fromJson(needs.setup.outputs.components) }}

    env:
      IMAGE_TYPE: operator
      STAGING_NAMESPACE: "default"
      LOCAL_HOST: ${{ secrets.LOCAL_HOST }}
      LOCAL_PORT: ${{ secrets.LOCAL_PORT }}
      SSH_GIT_REPO: ${{ secrets.SSH_GIT_REPO }}
      SSH_GITHUB_REPO: ${{ secrets.SSH_GITHUB_REPO }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_CONFIG: ${{ secrets.SSH_CONFIG }}
      CONNECT_SERVER: ${{ secrets.CONNECT_SERVER }}
      CONNECT_PORT: ${{ secrets.CONNECT_PORT }}
      CONNECT_KEY: ${{ secrets.CONNECT_KEY }}
      CONNECT_TIMEOUT: ${{ vars.CONNECT_TIMEOUT }}
      CONNECT_MODE: ${{ vars.CONNECT_MODE }}
      CONNECT_METHOD: ${{ secrets.CONNECT_METHOD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup bootstrap
        uses: ./containers/bootstrap

      - name: Set up and check env for ${{ matrix.component }}-${{env.IMAGE_TYPE}}
        run: |
          echo "setting up env with ${{ matrix.component }}"
          # check if the env is set
          echo PNAME=${{ matrix.component }}-$IMAGE_TYPE >> $GITHUB_ENV
          echo TNAME=${{ matrix.component }}-$IMAGE_TYPE >> $GITHUB_ENV
          
          # setting build number
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            RUN_NUMBER=${{ github.run_number }}
            OFFSET=${{ vars.OFFSET }}
            BUILD_NUMBER=$((RUN_NUMBER + OFFSET))
            if [[ "${{ inputs.PUBLISH_RELEASE }}" == 'true' ]]; then
              echo TAG="${{ inputs.PUBLISH_VERSION }}-$BUILD_NUMBER" >> $GITHUB_ENV
            else
              echo TAG="${{ inputs.PUBLISH_VERSION }}-SNAPSHOT-$BUILD_NUMBER" >> $GITHUB_ENV
            fi
            else
            BUILD_NUMBER="$(date +%Y%m%d)"
            DYNAMIC_VERSION=$(echo "${{ vars.PUBLISH_OPERATOR_VERSION }}" | awk -F. -v OFS=. '{ $2 = $2 + 1; $3 = 0; print $1, $2, $3 "_NIGHTLY" }')
            echo TAG="${DYNAMIC_VERSION}-$BUILD_NUMBER" >> $GITHUB_ENV
          fi
          cat $GITHUB_ENV

      - name: Run connect in background (search only)
        if: matrix.component == 'search'
        run: |
          connect -c "$GITHUB_WORKSPACE/.oss.json" >/dev/null 2>&1 &
          echo "Connect started with pid $!"
          sleep 5

      - name: Checkout ${{ matrix.component }}-${{env.IMAGE_TYPE}} repo
        run: |
          if [[ "${{ matrix.component }}" == "search" ]]; then
            git clone --depth 1 $SSH_GIT_REPO/$PNAME $GITHUB_WORKSPACE/$PNAME
          elif [[ "${{ matrix.component }}" == "runtime" ]]; then
            git clone $SSH_GITHUB_REPO/$PNAME $GITHUB_WORKSPACE/$PNAME
          fi

      - name: Update GitHub release version
        if: ${{ inputs.PUBLISH_RELEASE }}
        env:
          GH_TOKEN: ${{ secrets.REPO_PAT }}
        run: |
          VERSION=${{ inputs.PUBLISH_VERSION }}
          if [[ ! -z "$VERSION" && "$VERSION" =~ ^([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            echo "Updating GitHub release version to $VERSION"
            gh variable set PUBLISH_OPERATOR_VERSION --body "$VERSION"
          fi

      - name: Set up qemu for ${{ matrix.component }}-${{env.IMAGE_TYPE}}
        uses: docker/setup-qemu-action@v3

      - name: Set up docker buildx for ${{ matrix.component }}-${{env.IMAGE_TYPE}}
        uses: docker/setup-buildx-action@v3

      - name: Login to dockerhub for ${{ matrix.component }}-${{env.IMAGE_TYPE}}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build meta with ${{ matrix.component }}-${{env.IMAGE_TYPE}}
        id: meta
        working-directory: ${{ github.workspace }}/${{ env.PNAME }}
        run: |
          # make docker-buildx PLATFORMS="linux/amd64,linux/arm64" IMG="$REPO_NAME:$TAG"
          TAGS_OUTPUT=""
          
          # Define a helper function to generate tags for a given target name (TNAME)
          generate_tags_for() {
            local tname=$1
            local repo_name="${{ vars.DOCKER_REPO }}/${tname}"
            
            # 1. Add the unique build tag
            TAGS_OUTPUT="${TAGS_OUTPUT}${repo_name}:${{ env.TAG }}\n"
            
            # 2. Add the stable release tag if this is a release build
            if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ inputs.PUBLISH_RELEASE }}" == "true" ]]; then
              TAGS_OUTPUT="${TAGS_OUTPUT}${repo_name}:${{ inputs.PUBLISH_VERSION }}\n"
            fi
          }
          
          if [[ "${{ matrix.component }}" == 'search' ]]; then
            # If component is 'search', call the function for both vendors
            generate_tags_for "easysearch-${{env.IMAGE_TYPE}}"
            generate_tags_for "elasticsearch-${{env.IMAGE_TYPE}}"
          else
            # For 'runtime' or any other single component, call the function once
            generate_tags_for "${{ matrix.component }}-${{env.IMAGE_TYPE}}"
          fi
          
          echo "--- Generated Tags ---"
          echo -e "$TAGS_OUTPUT"
          echo "--------------------"
          
          # Set the multi-line output for the next step
          echo "tags<<EOF" >> $GITHUB_OUTPUT
          echo -e "$TAGS_OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Docker build and push ${{ matrix.component }}-${{env.IMAGE_TYPE}} with ${{env.REPO_NAME}}:${{env.TAG}}
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/${{ env.PNAME }}
          file: ${{ github.workspace }}/${{ env.PNAME }}/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          push: true

      - name: Deploy operator to staging k8s
        if: ${{ inputs.PUBLISH_RELEASE }}
        timeout-minutes: 10
        continue-on-error: true
        run: |
          deploy_component() {
            local component_name=$1
            local repo_name=$2
            local tag=$3
            local deployment_name=""

            if [[ "$component_name" == "runtime" ]]; then
              deployment_name="runtime-operator-controller-manager"
            else
              deployment_name="${component_name}-controller-manager"
            fi
            
            echo "--- Deploying ${component_name} ---"
            echo "Updating deployment '${deployment_name}' with image '${repo_name}:${tag}'"

            cat << EOF > /tmp/update_image.sh
            #!/bin/bash
            set -ex
            kubectl -n ${{ env.STAGING_NAMESPACE }} set image deployments.apps/${deployment_name} manager=${repo_name}:${tag}
            EOF
            ssh staging 'bash -s' < /tmp/update_image.sh
            echo "Finished deploying ${component_name}."
            echo "-------------------------"
          }

          if [[ "${{ matrix.component }}" == 'search' ]]; then
            deploy_component "easysearch" "${{ vars.DOCKER_REPO }}/easysearch-${{env.IMAGE_TYPE}}" "${{ env.TAG }}"
            deploy_component "elasticsearch" "${{ vars.DOCKER_REPO }}/elasticsearch-${{env.IMAGE_TYPE}}" "${{ env.TAG }}"
          else
            deploy_component "${{ matrix.component }}" "${{ vars.DOCKER_REPO }}/${{ matrix.component }}-${{env.IMAGE_TYPE}}" "${{ env.TAG }}"
          fi

  notify_on_failure:
    runs-on: ubuntu-latest
    needs: [setup, publish]
    if: failure()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send Feishu Notification on Failure
        env:
          FEISHU_BOT_URL: ${{ secrets.FEISHU_BOT_WEBHOOK_URL }}
          REPO_NAME: ${{ github.repository }}
          WORKFLOW_NAME: ${{ github.workflow }}
          RUN_ID: ${{ github.run_id }}
          ACTOR: ${{ github.triggering_actor }}
          SERVER_URL: ${{ github.server_url }}
        run: $GITHUB_WORKSPACE/scripts/feishu_message.sh
