name:  Test Analysis Plugins
defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
    inputs:
      PRODUCT:
        description: 'Setting Test Product'
        required: false
        type: choice
        options:
          - elasticsearch
          - opensearch
        default: 'elasticsearch'
      VERSION:
        description: 'Setting Test version'
        required: false
        default: '8.17.7'

jobs:
  test-analysis-plugins:
    name: Test Analysis Plugins for ${{ matrix.product }} @ ${{inputs.VERSION}}
    runs-on: ubuntu-latest
    env:
      TNAME: ${{ matrix.product }}
      VERSION: ${{ inputs.VERSION }}
    strategy:
      matrix:
        product:
          - ${{ inputs.PRODUCT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Search Engine with IK and Pinyin and strconvert plugins
        uses: ./search-engine
        with:
          engine-type: ${{ inputs.PRODUCT }}
          engine-version: ${{inputs.VERSION}}
          security-enabled: 'false'
          plugins: 'analysis-ik,analysis-pinyin,analysis-stconvert'

      - name: Verify IK Analyzer (${{ inputs.PRODUCT }})
        if: success()
        run: |
          sleep 15
          curl -X PUT "http://localhost:9200/test_ik_index" -H 'Content-Type: application/json' -d'
          {
            "settings": { "index.analysis.analyzer.default.tokenizer": "ik_max_word" }
          }'
          curl -X GET "http://localhost:9200/test_ik_index/_analyze?pretty" -H 'Content-Type: application/json' -d'
          {
            "text": "中华人民共和国"
          }'